### ISSUE TITLE
Please update 1.20.1 fabric

### ISSUE THREAD

**Issue by ChongYu668** [davidjjung/bellyflop#1]
I am a hardcore survival player, and this mod is very suitable for survival，please update 1.20.1 fabric

**Comment by davidjjung** [comment]
Hello--unfortunately, I have no experience or desire to port any mods to Fabric at this time. The mod currently depends on a mod exclusive to Forge (and it's also softly dependent on the mod Personality, which is also Forge-exclusive). That said, the mod is open-source and free to modify/redistribute under MIT License, so I won't object if somebody makes a Fabric fork. I can start by porting the mod to Forge 1.20.1 (which I just finished, and will upload soon). Hope this helps, and best of luck!
